version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: M0ng0**Ro0tp455

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: M0ng0**Ro0tp455

volumes:
  db_data:
  mongo-init.js: